import { useEffect, useState, type ReactNode } from 'react'
import QRCode from 'qrcode'
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import { ArrowDownLeft, ArrowLeftRight, ArrowUpRight, ChevronRight, CircleHelp, Copy, Eye, EyeOff, GripVertical, History, Home, Moon, MoreHorizontal, Plus, RotateCcw, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Sun, Trash2, Wallet as WalletIcon, X } from 'lucide-react'
import { allocation, assetValue, displayedPortfolioValue, formatMoney, formatToken } from './lib/calculations'
import { fictionalAddress } from './lib/generators'
import { useWalletStore } from './store/walletStore'
import type { Asset, BrandMark, LayoutMode, Tab, WalletTransaction } from './types/wallet'
import './index.css'

const tabs: { id: Tab; label: string; icon: typeof Home }[] = [
  { id: 'home', label: 'Home', icon: Home }, { id: 'wallet', label: 'Wallet', icon: WalletIcon },
  { id: 'activity', label: 'Activity', icon: History }, { id: 'swap', label: 'Swap', icon: ArrowLeftRight }, { id: 'settings', label: 'Settings', icon: Settings },
]
const chartData = [44, 49, 46, 54, 51, 59, 57, 64, 62, 68, 66, 72].map((value, index) => ({ day: index, value }))

function BrandGlyph({ mark, size = 16 }: { mark: BrandMark; size?: number }) {
  const source = mark === 'shield' ? '/larpwalletvibe/brand-mark-2.svg' : mark === 'hex' ? '/larpwalletvibe/brand-mark-3.svg' : '/larpwalletvibe/brand-mark-old.svg'
  return <img className="brand-glyph" src={source} width={size} height={size} alt="" />
}

export default function App() {
  const { appName, brandMark, theme, layout, setTheme } = useWalletStore()
  const [tab, setTab] = useState<Tab>('home')
  const [modal, setModal] = useState<'send' | 'receive' | 'swap' | 'buy' | 'asset' | null>(null)
  const [overlay, setOverlay] = useState<'profile' | 'wallet-menu' | 'help' | null>(null)
  const [selectedAsset, setSelectedAsset] = useState<Asset | null>(null)
  const [hideBalance, setHideBalance] = useState(false)
  useEffect(() => {
    document.body.classList.toggle('light-mode', theme === 'light')
    return () => document.body.classList.remove('light-mode')
  }, [theme])
  const openAsset = (asset: Asset) => { setSelectedAsset(asset); setModal('asset') }
  const openFlow = (flow: 'send' | 'receive' | 'swap' | 'buy') => setModal(flow)
  return <div className={`app-shell ${theme} layout-${layout}`}>
    <aside className="desktop-rail"><div className="brand-mark"><BrandGlyph mark={brandMark} size={16} /><span>{appName}</span></div><p className="rail-label">Workspace</p><nav>{tabs.map(({ id, label, icon: Icon }) => <button className={tab === id ? 'nav-item active' : 'nav-item'} key={id} onClick={() => setTab(id)}><Icon size={18} />{label}</button>)}</nav>{tab !== 'home' && <div className="rail-foot"><div className="mode-pill"><span /> LARP MODE</div><small>Local simulator</small></div>}</aside>
    <main className="main-column"><header className="topbar"><div className="mobile-brand"><BrandGlyph mark={brandMark} size={16} /><span>{appName}</span></div><div className="topbar-right">{tab !== 'home' && <span className="simulation-tag"><span /> Simulation</span>}<button className="icon-button" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')} aria-label={theme === 'dark' ? 'Switch to light mode' : 'Switch to dark mode'}>{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button className="icon-button" onClick={() => setOverlay('help')} aria-label="Open simulator guide"><CircleHelp size={18} /></button><button className="avatar" onClick={() => setOverlay('profile')} aria-label="Open profile">MR</button></div></header><div className="content"><Page tab={tab} onTab={setTab} onFlow={openFlow} onAsset={openAsset} onMenu={() => setOverlay('wallet-menu')} hideBalance={hideBalance} setHideBalance={setHideBalance} /></div></main>
    <nav className="bottom-nav">{tabs.map(({ id, label, icon: Icon }) => <button className={tab === id ? 'bottom-item active' : 'bottom-item'} key={id} onClick={() => setTab(id)}><Icon size={20} /><span>{label}</span></button>)}</nav>
    {modal && <Modal type={modal} asset={selectedAsset} onClose={() => { setModal(null); setSelectedAsset(null) }} />}
    {overlay && <UtilityOverlay type={overlay} onClose={() => setOverlay(null)} onProfile={() => setOverlay('profile')} />}
  </div>
}

function Page({ tab, onTab, onFlow, onAsset, onMenu, hideBalance, setHideBalance }: { tab: Tab; onTab: (tab: Tab) => void; onFlow: (flow: 'send' | 'receive' | 'swap' | 'buy') => void; onAsset: (asset: Asset) => void; onMenu: () => void; hideBalance: boolean; setHideBalance: (hidden: boolean) => void }) {
  if (tab === 'home') return <HomePage onFlow={onFlow} onAsset={onAsset} onMenu={onMenu} hideBalance={hideBalance} setHideBalance={setHideBalance} />
  if (tab === 'wallet') return <WalletPage onAsset={onAsset} />
  if (tab === 'activity') return <ActivityPage />
  if (tab === 'swap') return <><Header eyebrow="Fictional exchange" title="Swap" /><SwapForm /></>
  return <SettingsPage onTab={onTab} onMenu={onMenu} />
}
function Header({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: ReactNode }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div> }

function HomePage({ onFlow, onAsset, onMenu, hideBalance, setHideBalance }: { onFlow: (flow: 'send' | 'receive' | 'swap' | 'buy') => void; onAsset: (asset: Asset) => void; onMenu: () => void; hideBalance: boolean; setHideBalance: (hidden: boolean) => void }) {
  const state = useWalletStore(); const { walletName, fiat, assets, transactions } = state; const value = displayedPortfolioValue(state); const change = assets.reduce((sum, asset) => sum + assetValue(asset) * asset.change / 100, 0)
  return <><Header eyebrow="Personal workspace" title={walletName} action={<button className="icon-button" onClick={onMenu} aria-label="Open wallet actions"><MoreHorizontal size={20} /></button>} /><section className="portfolio-card"><div className="portfolio-top"><div><span className="muted-label">Total portfolio value</span><button className="eye-button" onClick={() => setHideBalance(!hideBalance)}>{hideBalance ? <EyeOff size={16} /> : <Eye size={16} />}</button></div><span className="live-dot"><span /> Fictional market</span></div><div className="portfolio-value">{hideBalance ? '••••••' : formatMoney(value, fiat)} <span className="value-currency">{fiat}</span></div><div className="portfolio-change"><span className="positive">↗ {formatMoney(change, fiat)}</span><span className="change-period">+2.36% today</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={132}><AreaChart data={chartData}><defs><linearGradient id="portfolio-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d4ff4f" stopOpacity={.28} /><stop offset="100%" stopColor="#d4ff4f" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="day" hide /><Tooltip contentStyle={{ background: '#20231e', border: '1px solid #34392d', borderRadius: 10 }} formatter={(v) => [`${v}k`, 'Value']} /><Area type="monotone" dataKey="value" stroke="#d4ff4f" strokeWidth={2.5} fill="url(#portfolio-fill)" /></AreaChart></ResponsiveContainer></div><div className="chart-labels"><span>Sep 12</span><span>Today</span></div></section><QuickActions onFlow={onFlow} /><section className="section-block"><div className="section-heading"><div><p className="eyebrow">Your collection</p><h2>Assets</h2></div><span className="count-pill">{assets.length}</span></div><div className="asset-list">{assets.map(asset => <AssetRow key={asset.id} asset={asset} fiat={fiat} portfolioValue={value} onClick={() => onAsset(asset)} />)}</div></section><section className="section-block recent-block"><div className="section-heading"><div><p className="eyebrow">Latest movement</p><h2>Recent activity</h2></div></div>{transactions.slice(0, 2).map(transaction => <TransactionRow key={transaction.id} transaction={transaction} fiat={fiat} />)}</section></>
}
function QuickActions({ onFlow }: { onFlow: (flow: 'send' | 'receive' | 'swap' | 'buy') => void }) { return <div className="quick-actions"><QuickAction icon={<ArrowUpRight />} label="Send" onClick={() => onFlow('send')} /><QuickAction icon={<ArrowDownLeft />} label="Receive" onClick={() => onFlow('receive')} /><QuickAction icon={<ArrowLeftRight />} label="Swap" onClick={() => onFlow('swap')} /><QuickAction icon={<Plus />} label="Buy" onClick={() => onFlow('buy')} /></div> }
function QuickAction({ icon, label, onClick }: { icon: ReactNode; label: string; onClick: () => void }) { return <button className="quick-action" onClick={onClick}><span>{icon}</span><small>{label}</small></button> }
function AssetRow({ asset, fiat, portfolioValue, onClick }: { asset: Asset; fiat: string; portfolioValue: number; onClick: () => void }) { return <button className="asset-row" onClick={onClick}><span className="token-icon" style={{ background: asset.color }}>{asset.icon}</span><span className="asset-main"><strong>{asset.name}</strong><small>{asset.symbol} · {allocation(asset, portfolioValue).toFixed(1)}%</small></span><span className="asset-numbers"><strong>{formatMoney(assetValue(asset), fiat)}</strong><small>{formatToken(asset.balance, asset.precision)} {asset.symbol} <em className={asset.change < 0 ? 'negative' : 'positive'}>{asset.change > 0 ? '+' : ''}{asset.change.toFixed(2)}%</em></small></span><ChevronRight size={16} className="row-chevron" /></button> }

function WalletPage({ onAsset }: { onAsset: (asset: Asset) => void }) { const { assets, fiat, deleteAsset, moveAsset } = useWalletStore(); const [showAdd, setShowAdd] = useState(false); const total = assets.reduce((sum, asset) => sum + assetValue(asset), 0); return <><Header eyebrow="Manage collection" title="Wallet" action={<button className="primary-button" onClick={() => setShowAdd(true)}><Plus size={16} /> Add asset</button>} /><div className="callout"><SlidersHorizontal size={18} /><div><strong>Larp Editor</strong><p>Shape your fictional wallet exactly how you want it to look.</p></div><ChevronRight size={16} /></div><div className="editor-list">{assets.map((asset, index) => <div className="editor-asset" key={asset.id}><GripVertical size={17} className="grip" /><AssetRow asset={asset} fiat={fiat} portfolioValue={total} onClick={() => onAsset(asset)} /><div className="asset-actions"><button onClick={() => moveAsset(asset.id, -1)} disabled={index === 0}>↑</button><button onClick={() => moveAsset(asset.id, 1)} disabled={index === assets.length - 1}>↓</button><button onClick={() => { if (window.confirm(`Remove ${asset.name}?`)) deleteAsset(asset.id) }}><Trash2 size={15} /></button></div></div>)}</div>{showAdd && <AssetForm onClose={() => setShowAdd(false)} />}</> }
function AssetForm({ onClose, asset }: { onClose: () => void; asset?: Asset }) { const addAsset = useWalletStore(state => state.addAsset); const updateAsset = useWalletStore(state => state.updateAsset); const [name, setName] = useState(asset?.name ?? ''); const [symbol, setSymbol] = useState(asset?.symbol ?? ''); const [balance, setBalance] = useState(String(asset?.balance ?? '')); const [price, setPrice] = useState(String(asset?.price ?? '')); const save = () => { if (!name || !symbol || Number(balance) < 0 || Number(price) < 0) return; if (asset) updateAsset(asset.id, { name, symbol: symbol.toUpperCase(), balance: Number(balance), price: Number(price) }); else addAsset({ name, symbol: symbol.toUpperCase(), balance: Number(balance), price: Number(price), change: 0, color: '#8c9b79', icon: symbol.slice(0, 1).toUpperCase(), precision: 4 }); onClose() }; return <div className="sheet-overlay"><div className="sheet compact-sheet"><div className="sheet-head"><div><p className="eyebrow">Larp editor</p><h2>{asset ? 'Edit asset' : 'Add asset'}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div><label>Asset name<input value={name} onChange={e => setName(e.target.value)} placeholder="Nebula Token" /></label><div className="form-grid"><label>Symbol<input value={symbol} onChange={e => setSymbol(e.target.value)} placeholder="NBL" /></label><label>Balance<input type="number" value={balance} onChange={e => setBalance(e.target.value)} placeholder="0" /></label></div><label>Fictional price<input type="number" value={price} onChange={e => setPrice(e.target.value)} placeholder="0.00" /></label><button className="primary-button full-button" onClick={save}>Save asset</button></div></div> }

function ActivityPage() { const { transactions, fiat, deleteTransaction } = useWalletStore(); return <><Header eyebrow="Local ledger" title="Activity" action={<button className="icon-button"><SlidersHorizontal size={18} /></button>} /><div className="filter-row"><button className="filter-chip active">All activity</button><button className="filter-chip">Received</button><button className="filter-chip">Sent</button><button className="filter-chip">Swaps</button></div><div className="activity-list">{transactions.map(transaction => <TransactionRow key={transaction.id} transaction={transaction} fiat={fiat} detailed onDelete={() => deleteTransaction(transaction.id)} />)}</div></> }
function TransactionRow({ transaction, fiat, detailed, onDelete }: { transaction: WalletTransaction; fiat: string; detailed?: boolean; onDelete?: () => void }) { const received = transaction.type === 'Received' || transaction.type === 'Bought'; return <div className="transaction-row"><span className={`transaction-icon ${received ? 'received' : 'sent'}`}>{received ? <ArrowDownLeft size={16} /> : <ArrowUpRight size={16} />}</span><div className="transaction-main"><strong>{transaction.type} <span>{transaction.assetSymbol}</span></strong><small>{transaction.date} · {transaction.status}</small>{detailed && <small className="mono">{transaction.address}</small>}</div><div className="transaction-amount"><strong className={received ? 'positive' : ''}>{received ? '+' : '-'}{formatToken(transaction.amount)} {transaction.assetSymbol}</strong><small>{formatMoney(transaction.fiatValue, fiat)}</small></div>{onDelete && <button className="delete-button" onClick={onDelete}><Trash2 size={14} /></button>}</div> }

function SwapForm() { const { assets } = useWalletStore(); const [from, setFrom] = useState(assets[1]?.id ?? ''); const [to, setTo] = useState(assets[3]?.id ?? ''); const [amount, setAmount] = useState('0.5'); const source = assets.find(asset => asset.id === from) ?? assets[0]; const destination = assets.find(asset => asset.id === to) ?? assets[1]; const output = source && destination ? Number(amount || 0) * source.price / destination.price : 0; return <div className="swap-panel"><div className="swap-note"><Sparkles size={16} />Local simulation · no network activity</div><div className="swap-input"><div><span>From</span><select value={from} onChange={e => setFrom(e.target.value)}>{assets.map(asset => <option value={asset.id} key={asset.id}>{asset.symbol} · {formatToken(asset.balance)} available</option>)}</select></div><input type="number" value={amount} onChange={e => setAmount(e.target.value)} /></div><div className="swap-switch"><ArrowDownLeft size={15} /></div><div className="swap-input"><div><span>To</span><select value={to} onChange={e => setTo(e.target.value)}>{assets.map(asset => <option value={asset.id} key={asset.id}>{asset.symbol}</option>)}</select></div><strong>{formatToken(output, destination?.precision)}</strong></div><div className="swap-details"><span>Rate <strong>1 {source?.symbol} = {formatToken((source?.price ?? 0) / (destination?.price ?? 1), 4)} {destination?.symbol}</strong></span><span>Network fee <strong>€0.84</strong></span><span>Price impact <strong className="positive">0.12%</strong></span></div><button className="primary-button full-button" onClick={() => window.alert('Swap simulated locally. No network activity occurred.')}>Review swap <ChevronRight size={16} /></button></div> }

function SettingsPage({ onTab, onMenu }: { onTab: (tab: Tab) => void; onMenu: () => void }) { const { walletName, fiat, portfolioMode, fixedPortfolioValue, setWalletName, setFiat, setPortfolioMode, setFixedPortfolioValue, reset } = useWalletStore(); const [editor, setEditor] = useState(false); return <><Header eyebrow="Control room" title="Settings" /><div className="settings-hero"><div className="settings-avatar">MR</div><div><strong>{walletName}</strong><p>{fiat} display · local only</p></div><button className="icon-button" onClick={onMenu} aria-label="Open wallet actions"><MoreHorizontal size={18} /></button></div><div className="settings-section"><p className="eyebrow">Larp editor</p><div className="settings-row" onClick={() => setEditor(!editor)}><span className="setting-icon lime"><SlidersHorizontal size={17} /></span><div><strong>Simulation controls</strong><small>Wallet name, portfolio mode, display currency</small></div><ChevronRight size={16} /></div>{editor && <div className="inline-editor"><label>Wallet name<input value={walletName} onChange={e => setWalletName(e.target.value)} /></label><label>Fiat currency<select value={fiat} onChange={e => setFiat(e.target.value as 'EUR' | 'USD' | 'GBP')}><option>EUR</option><option>USD</option><option>GBP</option></select></label><label>Portfolio mode<select value={portfolioMode} onChange={e => setPortfolioMode(e.target.value as 'calculated' | 'fixed')}><option value="calculated">Calculated from assets</option><option value="fixed">Fixed display value</option></select></label>{portfolioMode === 'fixed' && <label>Fixed portfolio value<input type="number" value={fixedPortfolioValue} onChange={e => setFixedPortfolioValue(Number(e.target.value))} /></label>}</div>}<div className="settings-row" onClick={() => onTab('wallet')}><span className="setting-icon blue"><WalletIcon size={17} /></span><div><strong>Manage assets</strong><small>Add, edit, remove, and reorder your collection</small></div><ChevronRight size={16} /></div><div className="settings-row" onClick={() => { if (window.confirm('Reset the simulator to demo data?')) reset() }}><span className="setting-icon coral"><RotateCcw size={17} /></span><div><strong>Reset simulator</strong><small>Restore the original fictional workspace</small></div><ChevronRight size={16} /></div></div><div className="safety-card"><ShieldCheck size={20} /><div><strong>Fictional wallet simulator</strong><p>LarpWallet does not hold, transfer, or manage real assets. Everything stays on this device.</p></div></div><div className="version-note">LarpWallet · v0.1.0 · SIMULATION / LARP MODE</div></> }

function UtilityOverlay({ type, onClose, onProfile }: { type: 'profile' | 'wallet-menu' | 'help'; onClose: () => void; onProfile: () => void }) {
  if (type === 'profile') return <ProfileOverlay onClose={onClose} />
  if (type === 'help') return <div className="sheet-overlay"><div className="sheet compact-sheet"><SheetHead title="Simulator guide" eyebrow="LarpWallet" onClose={onClose} /><div className="guide-list"><div><Sparkles size={17} /><span><strong>Everything is fictional</strong><small>Prices, addresses, balances, and activity are local demo data.</small></span></div><div><ShieldCheck size={17} /><span><strong>No network activity</strong><small>Nothing connects to banks, exchanges, blockchains, or real wallets.</small></span></div><div><SlidersHorizontal size={17} /><span><strong>Shape the scene</strong><small>Use Settings to rename the wallet, change fiat, and tune the display.</small></span></div></div><button className="secondary-button full-button" onClick={onClose}>Got it</button></div></div>
  const { walletAddress, reset } = useWalletStore()
  return <div className="sheet-overlay"><div className="sheet compact-sheet"><SheetHead title="Wallet actions" eyebrow="Midnight Relay" onClose={onClose} /><div className="action-menu"><button onClick={onProfile}><span className="menu-icon"><Settings size={16} /></span><span><strong>Open profile</strong><small>Wallet identity and display preferences</small></span><ChevronRight size={16} /></button><button onClick={() => navigator.clipboard?.writeText(walletAddress)}><span className="menu-icon"><Copy size={16} /></span><span><strong>Copy fictional address</strong><small>{walletAddress}</small></span><ChevronRight size={16} /></button><button onClick={() => { if (window.confirm('Reset the simulator to demo data?')) { reset(); onClose() } }}><span className="menu-icon danger"><RotateCcw size={16} /></span><span><strong>Reset simulator</strong><small>Restore the original fictional workspace</small></span><ChevronRight size={16} /></button></div></div></div>
}
function ProfileOverlay({ onClose }: { onClose: () => void }) { const { appName, brandMark, layout, walletName, walletAddress, fiat, setAppName, setBrandMark, setLayout, setWalletName, setFiat } = useWalletStore(); const [name, setName] = useState(walletName); const [title, setTitle] = useState(appName); const [mark, setMark] = useState(brandMark); const [layoutMode, setLayoutMode] = useState(layout); const save = () => { setAppName(title.trim() || appName); setBrandMark(mark); setLayout(layoutMode); setWalletName(name.trim() || walletName); onClose() }; return <div className="sheet-overlay"><div className="sheet compact-sheet"><SheetHead title="Profile" eyebrow="Wallet identity" onClose={onClose} /><div className="profile-card"><div className="profile-avatar"><BrandGlyph mark={mark} size={20} /></div><div><strong>{name || walletName}</strong><small>{title || appName} · Fictional local wallet</small></div></div><label>App name<input value={title} onChange={event => setTitle(event.target.value)} placeholder="LarpWallet" /></label><label>Brand choice<select value={mark} onChange={event => setMark(event.target.value as BrandMark)}><option value="spark">Mark 1</option><option value="shield">Mark 2</option><option value="hex">Mark 3</option></select></label><label>App layout<select value={layoutMode} onChange={event => setLayoutMode(event.target.value as LayoutMode)}><option value="relay">Relay · balanced</option><option value="vault">Vault · dense</option><option value="studio">Studio · spacious</option></select></label><label>Wallet name<input value={name} onChange={event => setName(event.target.value)} placeholder="Midnight Relay" /></label><label>Display currency<select value={fiat} onChange={event => setFiat(event.target.value as 'EUR' | 'USD' | 'GBP')}><option>EUR</option><option>USD</option><option>GBP</option></select></label><label>Fictional wallet address<div className="address-copy profile-address"><span>{walletAddress}</span><button onClick={() => navigator.clipboard?.writeText(walletAddress)}><Copy size={16} /></button></div></label><button className="primary-button full-button" onClick={save}>Save profile</button></div></div> }

function Modal({ type, asset, onClose }: { type: 'send' | 'receive' | 'swap' | 'buy' | 'asset'; asset: Asset | null; onClose: () => void }) { if (type === 'asset' && asset) return <AssetDetail asset={asset} onClose={onClose} />; if (type === 'receive') return <ReceiveModal onClose={onClose} />; if (type === 'swap') return <div className="sheet-overlay"><div className="sheet"><SheetHead title="Swap assets" eyebrow="Local simulation" onClose={onClose} /><SwapForm /></div></div>; if (type === 'send' || type === 'buy') return <FlowModal type={type} onClose={onClose} />; return null }
function SheetHead({ title, eyebrow, onClose }: { title: string; eyebrow: string; onClose: () => void }) { return <div className="sheet-head"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="icon-button" onClick={onClose}><X size={18} /></button></div> }
function AssetDetail({ asset, onClose }: { asset: Asset; onClose: () => void }) { const { fiat } = useWalletStore(); const state = useWalletStore(); return <div className="sheet-overlay"><div className="sheet"><SheetHead title="Asset detail" eyebrow={asset.symbol} onClose={onClose} /><div className="detail-token"><span className="token-icon large" style={{ background: asset.color }}>{asset.icon}</span><h2>{asset.name}</h2><strong>{formatMoney(assetValue(asset), fiat)}</strong><span className={asset.change < 0 ? 'negative' : 'positive'}>{asset.change > 0 ? '+' : ''}{asset.change.toFixed(2)}% today</span></div><div className="mini-chart"><ResponsiveContainer width="100%" height={150}><AreaChart data={asset.history.map((value, index) => ({ index, value }))}><Area type="monotone" dataKey="value" stroke={asset.color} fill={asset.color} fillOpacity={.12} strokeWidth={2} /><XAxis dataKey="index" hide /></AreaChart></ResponsiveContainer></div><div className="detail-stats"><span><small>Balance</small><strong>{formatToken(asset.balance, asset.precision)} {asset.symbol}</strong></span><span><small>Price</small><strong>{formatMoney(asset.price, fiat)}</strong></span><span><small>Allocation</small><strong>{allocation(asset, displayedPortfolioValue(state)).toFixed(1)}%</strong></span></div></div></div> }
function ReceiveModal({ onClose }: { onClose: () => void }) { const address = useWalletStore(state => state.walletAddress); const [qr, setQr] = useState(''); useEffect(() => { QRCode.toDataURL(address, { width: 220, margin: 2, color: { dark: '#d4ff4f', light: '#161914' } }).then(setQr) }, [address]); return <div className="sheet-overlay"><div className="sheet receive-sheet"><SheetHead title="Receive" eyebrow="Fictional address" onClose={onClose} /><div className="qr-frame">{qr && <img src={qr} alt="QR code for fictional local address" />}</div><p className="receive-copy">Share this address only inside your LarpWallet simulation.</p><div className="address-copy"><span>{address}</span><button onClick={() => navigator.clipboard?.writeText(address)}><Copy size={16} /></button></div><button className="secondary-button full-button" onClick={() => navigator.clipboard?.writeText(address)}><Copy size={16} /> Copy fictional address</button></div></div> }
function FlowModal({ type, onClose }: { type: 'send' | 'buy'; onClose: () => void }) { const { assets, fiat, addTransaction, updateAsset } = useWalletStore(); const [assetId, setAssetId] = useState(assets[0]?.id ?? ''); const [amount, setAmount] = useState(type === 'buy' ? '1000' : ''); const [note, setNote] = useState(''); const asset = assets.find(item => item.id === assetId) ?? assets[0]; const isBuy = type === 'buy'; const tokenAmount = isBuy ? Number(amount || 0) / (asset?.price ?? 1) : Number(amount || 0); const submit = () => { if (!asset || tokenAmount <= 0 || (!isBuy && tokenAmount > asset.balance)) return; updateAsset(asset.id, { balance: isBuy ? asset.balance + tokenAmount : asset.balance - tokenAmount }); addTransaction({ type: isBuy ? 'Bought' : 'Sent', assetId: asset.id, assetSymbol: asset.symbol, amount: tokenAmount, fiatValue: isBuy ? Number(amount) : tokenAmount * asset.price, date: 'Just now', status: 'Completed', address: fictionalAddress(), note }); onClose() }; return <div className="sheet-overlay"><div className="sheet"><SheetHead title={isBuy ? 'Buy asset' : 'Send asset'} eyebrow="Local simulation" onClose={onClose} /><div className="sim-banner"><ShieldCheck size={16} />No funds leave this device</div><label>Asset<select value={assetId} onChange={e => setAssetId(e.target.value)}>{assets.map(item => <option key={item.id} value={item.id}>{item.name} · {item.symbol}</option>)}</select></label><label>{isBuy ? `Fictional ${fiat} amount` : 'Amount'}<input type="number" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0.00" /></label>{!isBuy && <label>Recipient fictional address<input placeholder="larp_recipient_..." /></label>}<label>Note <span className="optional">Optional</span><input value={note} onChange={e => setNote(e.target.value)} placeholder="Add a note" /></label><div className="review-line"><span>Estimated received</span><strong>{formatToken(tokenAmount, asset?.precision)} {asset?.symbol} · {formatMoney(isBuy ? Number(amount || 0) : tokenAmount * (asset?.price ?? 0), fiat)}</strong></div><button className="primary-button full-button" onClick={submit}>{isBuy ? 'Simulate purchase' : 'Review send'} <ChevronRight size={16} /></button></div></div> }
